### ISSUE TITLE
Not installend MATE on CRUX 3.4

### ISSUE THREAD

**Issue by xlin** [mhoush/crux-mate#1]
=======> Build result:
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/lib/
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/share/
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/include/
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/include/bytesize/
-rw-r--r--  0 root   root     4105 Feb  1 01:06 usr/include/bytesize/bs_size.h
lrwxrwxrwx  0 root   root        0 Feb  1 01:06 usr/lib/libbytesize.so.1 -> libbytesize.so.1.0.0
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/lib/python2.7/
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/lib/pkgconfig/
-rwxr-xr-x  0 root   root      994 Feb  1 01:06 usr/lib/libbytesize.la
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/lib/python3.6/
-rwxr-xr-x  0 root   root    22968 Feb  1 01:06 usr/lib/libbytesize.so.1.0.0
lrwxrwxrwx  0 root   root        0 Feb  1 01:06 usr/lib/libbytesize.so -> libbytesize.so.1.0.0
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/lib/python3.6/site-packages/
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/lib/python3.6/site-packages/bytesize/
-rw-r--r--  0 root   root       27 Feb  1 01:06 usr/lib/python3.6/site-packages/bytesize/__init__.py
-rw-r--r--  0 root   root    21282 Feb  1 01:06 usr/lib/python3.6/site-packages/bytesize/bytesize.py
-rw-r--r--  0 root   root      303 Feb  1 01:06 usr/lib/pkgconfig/bytesize.pc
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/lib/python2.7/site-packages/
drwxr-xr-x  0 root   root        0 Feb  1 01:06 usr/lib/python2.7/site-packages/bytesize/
-rw-r--r--  0 root   root       27 Feb  1 01:06 usr/lib/python2.7/site-packages/bytesize/__init__.py
-rw-r--r--  0 root   root    21282 Feb  1 01:06 usr/lib/python2.7/site-packages/bytesize/bytesize.py
=======> ERROR: Footprint mismatch found:
NEW       drwxr-xr-x      root/root       usr/lib/python2.7/
NEW       drwxr-xr-x      root/root       usr/lib/python2.7/site-packages/
NEW       drwxr-xr-x      root/root       usr/lib/python2.7/site-packages/bytesize/
NEW       -rw-r--r--      root/root       usr/lib/python2.7/site-packages/bytesize/__init__.py
NEW       -rw-r--r--      root/root       usr/lib/python2.7/site-packages/bytesize/bytesize.py
=======> ERROR: Building '/usr/ports/mate/libbytesize/libbytesize#1.3-1.pkg.tar.gz' failed.

**Comment by mhoush** [comment]
Fixed in https://github.com/mhoush/crux-mate/commit/4ed7b11fd74962a1c49ae756f5e1c83e1d6c7c53, thanks for the report.
