### ISSUE TITLE
libtool:   error: cannot find the library '/usr/lib/libpangocairo-1.0.la' or unhandled argument '/usr/lib/libpangocairo-1.0.la'

### ISSUE THREAD

**Issue by mwgrient** [mhoush/crux-mate#2]
Hello, thank you for all the hard work on Mate for CRUX!

I have an error during the build of marco:

> CCLD     test-gravity
>   CCLD     focus-window
>   CCLD     test-resizing
> libtool:   error: cannot find the library '/usr/lib/libpangocairo-1.0.la' or unhandled argument '/usr/lib/libpangocairo-1.0.la'
> make[4]: *** [Makefile:442: test-gravity] Error 1
> make[4]: *** Waiting for unfinished jobs....
> libtool:   error: cannot find the library '/usr/lib/libpangocairo-1.0.la' or unhandled argument '/usr/lib/libpangocairo-1.0.la'
> make[4]: *** [Makefile:446: test-resizing] Error 1
> libtool:   error: cannot find the library '/usr/lib/libpangocairo-1.0.la' or unhandled argument '/usr/lib/libpangocairo-1.0.la'
> make[4]: *** [Makefile:438: focus-window] Error 1
> make[4]: Leaving directory '/usr/ports/mate/marco/work/src/marco-1.22.2/src/wm-tester'
> make[3]: *** [Makefile:1508: all-recursive] Error 1
> make[3]: Leaving directory '/usr/ports/mate/marco/work/src/marco-1.22.2/src'
> make[2]: *** [Makefile:726: all] Error 2
> make[2]: Leaving directory '/usr/ports/mate/marco/work/src/marco-1.22.2/src'
> make[1]: *** [Makefile:458: all-recursive] Error 1
> make[1]: Leaving directory '/usr/ports/mate/marco/work/src/marco-1.22.2'
> make: *** [Makefile:390: all] Error 2
> =======> ERROR: Building '/usr/ports/mate/marco/marco#1.22.2-1.pkg.tar.gz' failed.
> prt-get: error while install
> 
> -- Packages where install failed
> marco

Maybe it is because of my name is Marco too, that marco won't build? :-)
I understand that *.la files are needed for dependencies?
Any thoughts/suggestions on this? I  do have pango/cairo installed and there is a libpangocairo.so file.

Regards, Marco

**Comment by TimB87** [comment]
Hi Marco,

some projects don't provide la files anymore, it was libtool junk, iirc. Please try the following

> prt-cache update -fr \
>         `for f in $(grep -lr "libpangocairo-1.0.la" /usr/lib/ 2> /dev/null | sed 's|.*/||'); \
>         do prt-get fsearch $f | grep '^Found in' | sed -e 's|.*/||' -e 's|:$||'; \
>         done | sort -u | xargs prt-cache isinst | grep -e 'is installed' | awk '{ print $2 }'`;

This may take some time and need 2-3 runs. Good luck!

**Comment by mwgrient** [comment]
Wow, thanks for the quick answer!

When applaying this command (as root) as a one-liner I get:

`syntax error near unexpected token `do'

**Comment by TimB87** [comment]
sorry, that's github doing markup on the code, please have a look at this paste: http://dpaste.com/2PZB7X8

**Comment by mwgrient** [comment]
Solved!  And my longest command ever! :-)
Now building marco.

**Comment by TimB87** [comment]
Save the command for whenever you get that kind of problem, as it might just solve it :-)

**Comment by mhoush** [comment]
Hey, Marco, glad you're getting some use out of the MATE ports! As Tim says there's been some removal/deprecation of libtool .la files necessitating a bunch of rebuilds. Glad you've got it sorted.

**Comment by exton** [comment]
TimB87,
Please resend the code above. I need it to be able to install gtk3. The code at http://dpaste.com/2PZB7X8 is gone.

**Comment by TimB87** [comment]
```
#!/bin/bash
# rebuild-lib libatk-1.0.la for example
rebuild-lib() {
    prt-cache update -fr -if -im -is \
        `for f in $(grep -lr "$*" /usr/lib/ 2> /dev/null | sed 's|.*/||'); \
        do prt-get fsearch $f | grep '^Found in' | sed -e 's|.*/||' -e 's|:$||'; \
        done | sort -u | xargs prt-cache isinst | grep -e 'is installed' | awk '{ print $2 }'`; 
}
```
@exton here you go
