### ISSUE TITLE
almost there :-) >> idocalendarmenuitem.c:109:13: error: G_ADD_PRIVATE [-Werror]

### ISSUE THREAD

**Issue by mwgrient** [mhoush/crux-mate#3]
Hi,
I am hoping to use MATE soon, but encountered this error on building module: ayatana-ido

> /usr/include/glib-2.0/gobject/gtype.h:1308:10: note: declared here
>  void     g_type_class_add_private       (gpointer                    g_class,
>           ^~~~~~~~~~~~~~~~~~~~~~~~
> idocalendarmenuitem.c: In function 'ido_calendar_menu_item_init':
> idocalendarmenuitem.c:109:13: error: G_ADD_PRIVATE [-Werror]
>    priv = item->priv = IDO_CALENDAR_MENU_ITEM_GET_PRIVATE (item);
>              ^~~~~~~~~~~~~~~
> idocalendarmenuitem.c: In function 'ido_calendar_menu_item_finalize':
> idocalendarmenuitem.c:139:13: error: G_ADD_PRIVATE [-Werror]
>    IdoCalendarMenuItemPrivate *priv = IDO_CALENDAR_MENU_ITEM_GET_PRIVATE (item);
>              ^~~~~~~~~~~~~~~
>   CC       idomessagedialog.lo

```
I have tried:
- different versions of ayatana-ido;
- searching for configure options;
- searching google...
```

I understand it is not your source file. So if you wish to take the error to the author it is ok. 
Regards, Marco.

**Comment by TimB87** [comment]
Try
`CFLAGS="-Wno-error" \`
one line above the configure line please.

**Comment by mwgrient** [comment]
It's building again! One to remember, did the same on 'libayatana-indicator' because the same error occurs. And building again...
Thank you TimB87!

**Comment by mwgrient** [comment]
I had to upgrade 'engrampa' to the latest version (1.23.1 release), but now I have a running MATE desktop with CRUX.
have a nice day,
Marco

**Comment by TimB87** [comment]
FYI: Everything uneven in version number (as in 1.**23**.1) is the beta branch for the upcoming release.

Edit: at least for mate. This also applies to some other projects.

**Comment by mhoush** [comment]
Worked around in https://github.com/mhoush/crux-mate/commit/71d81988683f68baf69f12d10ffbb83c37166833, thanks for reporting.
