### ISSUE TITLE
cairomm / cairomm12

### ISSUE THREAD

**Issue by mwgrient** [mhoush/crux-mate#4]
Hello.
I am installing MATE on a CRUX machine. I run into light problems with cairomm.

It appears that in contrib, there are two packages of cairomm. MATE needs **cairomm12** for some reason, but installing cairomm. And then there are some problems and the build stops.

Just to let you know!
Regards, Marco.

**Comment by TimB87** [comment]
Hi @mwgrient 
These changes were recently introduced. In the meantime you can just `prt-get depinst cairomm12` and continue where it stopped before.

**Comment by mhoush** [comment]
Hey, @mwgrient, thanks for the report, but this dependency is not in the MATE tree. Rather it comes from contrib/pangomm which is in the dependency list for MATE but not a MATE package itself. I've reported it to the maintainer.
